# Generated by Django 4.2.5 on 2024-06-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activity',
            field=models.TextField(blank=True, null=True),
        ),
    ]
